version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db

  postgres:
    image: postgres:15
    container_name: adonis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
